name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train and Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set +e  # Devam etme modu, herhangi bir hatayı yoksayar
          pip install -r requirements.txt || true
          python train.py || true

          # Dosyalar mevcutsa raporu oluşturur, aksi halde işlemi bitirir
          if [ -f metrics.txt ] && [ -f plot.png ]; then
            cat metrics.txt >> report.md
            echo '![](./plot.png "Confusion Matrix")' >> report.md
            cml comment create report.md
          else
            echo "metrics.txt or plot.png not found. Skipping report creation."
          fi
        shell: bash
